---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list: recipe[rax-magento::default]

  - name: lsyncd
    run_list: recipe[rax-magento::lsyncd]
    attributes:
      rax:
        lsyncd:
          clients:
          - 192.168.99.99
